project:
  type: website
  output-dir: _site

website:
  title: "[Your Practice Name]"
  favicon: ""
  navbar: false

format:
  html:
    theme: none
    css: styles.css
    toc: false
    page-layout: full
