project:
  type: website
  output-dir: docs
  resources:
    - CNAME

website:
  title: "STEP-CM Analytics"
  navbar:
    left:
      - text: "About"
        href: index.html#about
      - text: "Services"
        href: index.html#services
      - text: "Background"
        href: index.html#credentials
      - text: "Contact"
        href: index.html#contact


format:
  html:
    theme: default
    css: styles.css
    toc: false
    page-layout: full
