project:
  type: website
  output-dir: docs
  resources:
    - CNAME

website:
  title: "STEP-CM Analytics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: B.AAJ-Understanding_your_data.qmd
        text: Understanding Your Data

format:
  html:
    theme: none
    css: styles.css
    toc: false
    page-layout: full
